/**
 * The one TypeScript implementation of the reach algebra. Pure: no I/O, no imports, no clock.
 *
 * Why this exists at all: the deployed web app cannot call the Python engine, because ADR 0003
 * keeps `apps/web` free of workspace dependencies so a monorepo build order can never break the
 * deployment. So the declared surfaces and ledger are recomputed here, from the committed JSON,
 * which means the deployed page renders derived product data rather than a fixture.
 *
 * This is a MIRROR, and mirrors rot. Two things keep it honest:
 *   1. `tests/parity.test.mjs` compares this module's output, object for object, against a
 *      fixture generated by running `python -m consentreach_lint`.
 *   2. Every ordering rule below matches the Python exactly, including tie-breaks, because the
 *      parity test compares whole objects rather than counts.
 *
 * This module has zero imports on purpose: that lets Node's test runner load it directly, so the
 * parity test runs without a bundler, a compile step, or a path-mapping trick.
 *
 * If you change a rule here, change it in `services/engine/src/consentreach_lint/reach.py` too,
 * regenerate the fixture with `node scripts/gen-parity-fixture.mjs`, and let the test fail until
 * both agree.
 */

export const AUTOMATION_RANK: Readonly<Record<string, number>> = Object.freeze({
  none: 0,
  human_review: 1,
  human_approval: 2,
  automated: 3,
})

export const EFFECT_RANK: Readonly<Record<string, number>> = Object.freeze({
  none: 0,
  advisory: 1,
  binding: 2,
  dispositive: 3,
})

export const SENSITIVE_DATA_CLASSES: ReadonlySet<string> = new Set([
  'health',
  'biometric',
  'genetic',
  'precise_location',
  'financial',
])

export const REASON_SEVERITY: Readonly<Record<string, number>> = Object.freeze({
  'grant-escalation': 100,
  'grant-withdrawn': 80,
  'grant-expired': 80,
  'no-active-grant': 60,
  'data-class-not-covered': 60,
})

export const HUNK_SEVERITY: Readonly<Record<string, number>> = Object.freeze({
  'effect-escalation': 100,
  'automation-escalation': 90,
  'reach-withdrawal': 80,
  'scope-creep': 60,
  benign: 0,
})

export type HunkClass =
  'effect-escalation' | 'automation-escalation' | 'reach-withdrawal' | 'scope-creep' | 'benign'

export type BlockerReason =
  'grant-escalation' | 'grant-withdrawn' | 'grant-expired' | 'no-active-grant' | 'data-class-not-covered'

export interface ProcessingActivity {
  readonly id: string
  readonly purpose: string
  readonly subjectClass: string
  readonly automation: string
  readonly decisionEffect: string
  readonly dataClasses: readonly string[]
  readonly legalBasis: string
}

export interface ProcessingSurface {
  readonly system: string
  readonly epoch: string
  readonly note?: string
  readonly activities: readonly ProcessingActivity[]
}

export interface ConsentGrant {
  readonly id: string
  readonly subjectClass: string
  readonly purposes: readonly string[]
  readonly activities: readonly string[]
  readonly dataClasses: readonly string[]
  readonly legalBasis: string
  readonly automation: string
  readonly decisionEffect: string
  readonly validFrom: string
  readonly validUntil: string
  readonly status: 'active' | 'withdrawn'
}

export interface ConsentLedger {
  readonly note?: string
  readonly grants: readonly ConsentGrant[]
}

export interface Hunk {
  readonly op: 'add' | 'remove' | 'change'
  readonly id: string
  readonly fields: readonly string[]
  readonly klass: HunkClass
  readonly severity: number
}

export interface UncoveredTuple {
  readonly activityId: string
  readonly subjectClass: string
  readonly purpose: string
  readonly dataClasses: readonly string[]
  readonly automation: string
  readonly decisionEffect: string
  readonly legalBasis: string
  readonly reason: BlockerReason
  readonly reasonSeverity: number
  readonly blockers: readonly BlockerReason[]
}

export interface Coverage {
  readonly activities: number
  readonly consentActivities: number
  readonly covered: number
  readonly uncovered: number
  readonly outOfScope: number
  readonly coverageRatio: number
}

export interface ReachDiffResult {
  readonly asOf: string
  readonly hunks: readonly Hunk[]
  readonly uncovered: readonly UncoveredTuple[]
  readonly outOfScope: readonly string[]
  readonly coverage: Coverage
  readonly stats: {
    readonly hunks: number
    readonly unchangedActivities: number
    readonly byClass: Readonly<Record<string, number>>
    readonly maxSeverity: number
    readonly orphans: number
  }
}

export interface Violation {
  readonly rule: string
  readonly severity: 'high' | 'medium' | 'info'
  readonly subject: string
  readonly detail: string
}

export interface ValidateResult {
  readonly violations: readonly Violation[]
  readonly counts: { readonly high: number; readonly medium: number; readonly info: number }
  readonly clean: boolean
  readonly checkedActivities: number
  readonly checkedGrants: number
}

/**
 * Value equality, not reference equality.
 *
 * `dataClasses`, `purposes` and `activities` are arrays, and two JSON documents describing the
 * same scope always produce distinct array instances. Comparing them with `!==` reported every
 * unchanged activity as modified; Python compares by value, so this must too.
 */
const sameValue = (left: unknown, right: unknown): boolean => {
  if (Array.isArray(left) && Array.isArray(right)) {
    return left.length === right.length && left.every((item, index) => sameValue(item, right[index]))
  }
  return left === right
}

/**
 * Total lookup into a rank or severity table.
 *
 * `noUncheckedIndexedAccess` is on, and these tables are indexed by strings that come from data,
 * so every read would otherwise be `number | undefined`. Defaulting to 0 keeps an unknown key
 * from silently becoming the most severe thing on the page.
 */
const rankOf = (table: Readonly<Record<string, number>>, key: string): number => table[key] ?? 0

const matches = (pattern: string, value: string): boolean => pattern === '*' || pattern === value

const inList = (patterns: readonly string[], value: string): boolean =>
  patterns.includes('*') || patterns.includes(value)

const inWindow = (grant: ConsentGrant, asOf: string): boolean =>
  grant.validFrom <= asOf && (grant.validUntil === 'forever' || asOf <= grant.validUntil)

const axesMatch = (grant: ConsentGrant, activity: ProcessingActivity): boolean =>
  grant.legalBasis === activity.legalBasis &&
  matches(grant.subjectClass, activity.subjectClass) &&
  inList(grant.purposes, activity.purpose) &&
  inList(grant.activities, activity.id)

const dataCovers = (grant: ConsentGrant, activity: ProcessingActivity): boolean =>
  grant.dataClasses.includes('*') || activity.dataClasses.every((name) => grant.dataClasses.includes(name))

const escalationOk = (grant: ConsentGrant, activity: ProcessingActivity): boolean =>
  rankOf(AUTOMATION_RANK, grant.automation) >= rankOf(AUTOMATION_RANK, activity.automation) &&
  rankOf(EFFECT_RANK, grant.decisionEffect) >= rankOf(EFFECT_RANK, activity.decisionEffect)

/** Every reason this activity is uncovered, most severe first. Empty means covered. */
export function blockersFor(
  activity: ProcessingActivity,
  grants: readonly ConsentGrant[],
  asOf: string,
): readonly BlockerReason[] {
  const structural = grants.filter((grant) => axesMatch(grant, activity))
  const live = structural.filter((grant) => grant.status === 'active' && inWindow(grant, asOf))

  if (live.length > 0) {
    const found: BlockerReason[] = []
    if (!live.some((grant) => dataCovers(grant, activity))) found.push('data-class-not-covered')
    if (!live.some((grant) => escalationOk(grant, activity))) found.push('grant-escalation')
    if (found.length > 0) {
      return found.sort(
        (a, b) => rankOf(REASON_SEVERITY, b) - rankOf(REASON_SEVERITY, a) || a.localeCompare(b),
      )
    }
    return []
  }

  if (structural.some((grant) => grant.status === 'withdrawn')) return ['grant-withdrawn']
  if (structural.length > 0) return ['grant-expired']
  return ['no-active-grant']
}

function classifyChange(before: ProcessingActivity, after: ProcessingActivity): HunkClass {
  if ((EFFECT_RANK[after.decisionEffect] ?? 0) > (EFFECT_RANK[before.decisionEffect] ?? 0)) {
    return 'effect-escalation'
  }
  if ((AUTOMATION_RANK[after.automation] ?? 0) > (AUTOMATION_RANK[before.automation] ?? 0)) {
    return 'automation-escalation'
  }
  const widening =
    before.purpose !== after.purpose ||
    before.subjectClass !== after.subjectClass ||
    after.dataClasses.some((name) => !before.dataClasses.includes(name)) ||
    before.legalBasis !== after.legalBasis
  return widening ? 'scope-creep' : 'benign'
}

/** The mirror of `reach.py`'s `reach_diff`. */
export function reachDiff(input: {
  before: readonly ProcessingActivity[]
  after: readonly ProcessingActivity[]
  ledger: ConsentLedger
  ledgerBefore?: ConsentLedger
  asOf: string
}): ReachDiffResult {
  const { before, after, ledger, asOf } = input
  const grants = ledger.grants

  const beforeById = new Map(before.map((item) => [item.id, item]))
  const afterById = new Map(after.map((item) => [item.id, item]))

  const hunks: Hunk[] = []
  for (const id of [...afterById.keys()].sort()) {
    if (beforeById.has(id)) continue
    const item = afterById.get(id) as ProcessingActivity
    const klass: HunkClass = item.legalBasis === 'consent' ? 'scope-creep' : 'benign'
    hunks.push({ op: 'add', id, fields: [], klass, severity: rankOf(HUNK_SEVERITY, klass) })
  }
  for (const id of [...beforeById.keys()].sort()) {
    if (afterById.has(id)) continue
    hunks.push({ op: 'remove', id, fields: [], klass: 'benign', severity: rankOf(HUNK_SEVERITY, 'benign') })
  }

  let unchanged = 0
  for (const id of [...beforeById.keys()].sort()) {
    const right = afterById.get(id)
    if (!right) continue
    const left = beforeById.get(id) as ProcessingActivity
    const fields = (Object.keys(right) as (keyof ProcessingActivity)[])
      .filter((key) => key !== 'id' && !sameValue(left[key], right[key]))
      .sort()
    if (fields.length === 0) {
      unchanged += 1
      continue
    }
    const klass = classifyChange(left, right)
    hunks.push({ op: 'change', id, fields, klass, severity: rankOf(HUNK_SEVERITY, klass) })
  }

  if (input.ledgerBefore) {
    const previous = new Map(input.ledgerBefore.grants.map((grant) => [grant.id, grant]))
    for (const grant of grants) {
      const earlier = previous.get(grant.id)
      if (!earlier) continue
      const wasEffective = earlier.status === 'active' && inWindow(earlier, asOf)
      const isEffective = grant.status === 'active' && inWindow(grant, asOf)
      if (wasEffective && !isEffective) {
        const fields = (Object.keys(grant) as (keyof ConsentGrant)[])
          .filter((key) => key !== 'id' && !sameValue(earlier[key], grant[key]))
          .sort()
        hunks.push({
          op: 'change',
          id: grant.id,
          fields,
          klass: 'reach-withdrawal',
          severity: rankOf(HUNK_SEVERITY, 'reach-withdrawal'),
        })
      }
    }
  }

  hunks.sort((a, b) => b.severity - a.severity || a.id.localeCompare(b.id) || a.op.localeCompare(b.op))

  const uncovered: UncoveredTuple[] = []
  const outOfScope: string[] = []
  let covered = 0
  for (const activity of [...after].sort((a, b) => a.id.localeCompare(b.id))) {
    if (activity.legalBasis !== 'consent') {
      outOfScope.push(activity.id)
      continue
    }
    const blockers = blockersFor(activity, grants, asOf)
    const head = blockers[0]
    if (head === undefined) {
      covered += 1
      continue
    }
    uncovered.push({
      activityId: activity.id,
      subjectClass: activity.subjectClass,
      purpose: activity.purpose,
      dataClasses: [...activity.dataClasses].sort(),
      automation: activity.automation,
      decisionEffect: activity.decisionEffect,
      legalBasis: activity.legalBasis,
      reason: head,
      reasonSeverity: rankOf(REASON_SEVERITY, head),
      blockers,
    })
  }
  uncovered.sort((a, b) => b.reasonSeverity - a.reasonSeverity || a.activityId.localeCompare(b.activityId))

  const consentTotal = after.length - outOfScope.length
  const byClass: Record<string, number> = {
    'effect-escalation': 0,
    'automation-escalation': 0,
    'reach-withdrawal': 0,
    'scope-creep': 0,
    benign: 0,
  }
  for (const hunk of hunks) byClass[hunk.klass] = (byClass[hunk.klass] ?? 0) + 1

  return {
    asOf,
    hunks,
    uncovered,
    outOfScope: outOfScope.sort(),
    coverage: {
      activities: after.length,
      consentActivities: consentTotal,
      covered,
      uncovered: uncovered.length,
      outOfScope: outOfScope.length,
      coverageRatio: consentTotal === 0 ? 1 : Number((covered / consentTotal).toFixed(6)),
    },
    stats: {
      hunks: hunks.length,
      unchangedActivities: unchanged,
      byClass,
      maxSeverity: hunks.reduce((max, hunk) => Math.max(max, hunk.severity), 0),
      orphans: uncovered.length,
    },
  }
}

/** The mirror of `reach.py`'s `validate_surface`. */
export function validateSurface(input: {
  surface: { readonly activities: readonly ProcessingActivity[] }
  ledger: ConsentLedger
}): ValidateResult {
  const { activities } = input.surface
  const grants = input.ledger.grants
  const violations: Violation[] = []

  for (const activity of [...activities].sort((a, b) => a.id.localeCompare(b.id))) {
    if (['binding', 'dispositive'].includes(activity.decisionEffect) && activity.automation === 'automated') {
      violations.push({
        rule: 'machine-decided-binding-effect',
        severity: 'high',
        subject: activity.id,
        detail:
          'a machine decides a binding or dispositive outcome; consent cannot be reused from a human-reviewed version of this activity',
      })
    }
    const sensitive = activity.dataClasses.filter((name) => SENSITIVE_DATA_CLASSES.has(name)).sort()
    if (activity.legalBasis !== 'consent' && sensitive.length > 0) {
      violations.push({
        rule: 'sensitive-data-without-consent',
        severity: 'high',
        subject: activity.id,
        detail: `touches ${sensitive.join(', ')} under basis ${activity.legalBasis}`,
      })
    }
    if (activity.dataClasses.length === 0) {
      violations.push({
        rule: 'undeclared-data-classes',
        severity: 'medium',
        subject: activity.id,
        detail: 'no data classes declared, so no grant can be shown to cover it',
      })
    }
  }

  for (const grant of [...grants].sort((a, b) => a.id.localeCompare(b.id))) {
    const axes: readonly [string, string, readonly string[]][] = [
      ['purposes', 'wildcard-purpose-grant', grant.purposes],
      ['activities', 'wildcard-activity-grant', grant.activities],
      ['dataClasses', 'wildcard-data-grant', grant.dataClasses],
    ]
    for (const [field, rule, values] of axes) {
      if (values.includes('*')) {
        violations.push({
          rule,
          severity: 'medium',
          subject: grant.id,
          detail: `${field} contains '*', so this grant authorises more than it names; it will sweep in processing nobody asked about`,
        })
      }
    }
    if (grant.subjectClass === '*') {
      violations.push({
        rule: 'wildcard-cohort-grant',
        severity: 'medium',
        subject: grant.id,
        detail: "subjectClass is '*', so this grant covers cohorts it never named",
      })
    }
    if (grant.status === 'active' && grant.validUntil !== 'forever') {
      violations.push({
        rule: 'expiring-grant',
        severity: 'info',
        subject: grant.id,
        detail: `lapses on ${grant.validUntil}; activities covered by it alone will be orphaned on that date`,
      })
    }
  }

  const order: Record<Violation['severity'], number> = { high: 0, medium: 1, info: 2 }
  violations.sort(
    (a, b) =>
      order[a.severity] - order[b.severity] ||
      a.rule.localeCompare(b.rule) ||
      a.subject.localeCompare(b.subject),
  )
  const counts = { high: 0, medium: 0, info: 0 }
  for (const violation of violations) counts[violation.severity] += 1

  return {
    violations,
    counts,
    clean: violations.length === 0,
    checkedActivities: activities.length,
    checkedGrants: grants.length,
  }
}
